<?php
$title = 'ReactPage';
$this->headTitle($title);
?>

<h2> Welcome to the ReactPage</h2>
<div class="container" id="react-container">
    
</div>
<script src=<?=$this->basePath('js/react-0.14.3.min.js')?>></script>
<script src=<?=$this->basePath('js/react-dom-0.14.3.min.js')?>></script>
<!-- <script src='https://unpkg.com/babel-standalone@6/babel.min.js'></script> -->
<script src=<?=$this->basePath('js/main.js')?>></script>
